redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
command = "bun install && bun run build"
publish = "dist"
base = "dot-web-main"

[build.cache]
paths = [
  "node_modules",
  ".bun",
  "bun.lockb"
]

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]
